name: Auto Render PlantUML Diagrams

on:
  push:
    paths:
      - 'diagrams/**/*.puml'
  workflow_dispatch:

jobs:
  render-and-commit:
    runs-on: ubuntu-latest
    name: Generate and Commit UML Diagrams

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use a token explicitly for push

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Generate SVG diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: "-tsvg diagrams/**/*.puml"

      - name: Commit and Push SVGs
        run: |
          git add diagrams/**/*.svg
          git diff --cached --quiet || (git commit -m "Auto-update PlantUML diagrams" && git push)
        env:
          GIT_AUTHOR_NAME: GitHub Actions Bot
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions Bot
          GIT_COMMITTER_EMAIL: actions@github.com
          # Use the default token for push
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
