name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'diagrams/**/*.puml'
      - '.github/workflows/plantuml-render.yml'
  workflow_dispatch:

jobs:
  render-plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up output directory
        run: mkdir -p diagrams/png

      - name: Render PlantUML diagrams
        run: |
          docker run --rm -v ${{ github.workspace }}/diagrams:/workspace plantuml/plantuml -tpng -o png *.puml

      - name: Commit and push rendered PNGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Render PlantUML diagrams [skip ci]"
          branch: ${{ github.ref }}
          file_pattern: diagrams/png/*.png