name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main
      - master

jobs:
  render_diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render PlantUML diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-tutxt diagrams/*.txt'
      - name: Display diagrams
        run: cat diagrams/*.utxt

      - name: Commit generated diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add diagrams/*.png
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate PlantUML diagrams"
            git push
          fi