name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'diagrams/**/*.puml'
  pull_request:
    paths:
      - 'diagrams/**/*.puml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    name: Render UML Diagrams
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SVGs from PUML
        uses: holowinski/plantuml-github-action@main
        with:
          args: "-tsvg diagrams/**/*.puml"

      - name: Upload Rendered Diagrams as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-diagrams
          path: diagrams/**/*.svg
