name: Generate PlantUML diagrams

on:
  push:
    paths:
      - '**.puml'
      - '**.plantuml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PlantUML diagrams
        uses: 
          - name: Run PlantUML Action
            uses: <<!nav>>plantuml/plantuml-action@v1
            with:
              args: -outputdir docs/diagrams -serverurl https://www.plantuml.com/plantuml
              files: "*.puml"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: generate PlantUML diagrams"
          branch: main


      - name: Commit generated diagrams
        # FIX 3: This step is now correctly indented
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # FIX 4: Adding the correct file type (.png)
          git add diagrams/*.png
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate PlantUML diagrams"
            git push
          fi